More work on default test.

diff --git a/scripts/include/call b/scripts/include/call
--- a/scripts/include/call
+++ b/scripts/include/call
@@ -22,6 +22,8 @@ if [[ -z ${NODES} ]]; then
 fi
 
 call_ssh_nodes() {
+    local NODE=
+
     for NODE in ${NODES[@]}; do
         echo "${NODE}:"
         ${SCRIPT_DIR}/ssh $NODE $@
@@ -34,6 +36,7 @@ call_ssh_nodes_p() {
 
 call_ssh_nodes_s() {
     SLEEP_TIMER="0"
+    local NODE=
 
     for NODE in ${NODES[@]}; do
         sleep ${SLEEP_TIMER}
@@ -49,16 +52,16 @@ call_rpc() {
     FORWARD_PORT=`cat ${DATA_DIR}/${CALL_NODE}/metadata/forward.5001`
 
     if [ -z ${FORWARD_PORT} ]; then
-        echo "Could not find forward port for ${CALL_NODE}"
+        >&2 echo "Could not find forward port for ${CALL_NODE}"
         exit -1
     fi
 
     NODE_URL="scgi://localhost:${FORWARD_PORT}"
-    CALL_CMD="$RPC_CLIENT -s $NODE_URL $@"
+    CALL_CMD="${RPC_CLIENT} -s ${NODE_URL} $@"
 
     [ "${DEBUG}" == "1" ] && >&2 echo "${CALL_CMD}"
 
-    $CALL_CMD
+    ${CALL_CMD}
 }
 
 call_rpc_nodes() {
@@ -78,14 +81,17 @@ call_rpc_awk_nodes() {
 wait_for_nodes() {
     SECONDS=0
 
-    local method="$1"
+    local timeout="${WAIT_TIMEOUT:-10}"
+    local nodes="${WAIT_NODES:-${NODES}}"
+
     local failed="invalid"
+    local method="$1"
     shift
 
-    echo "wait_for_node: ${remaining} calling '${method}' $i $@"
+    #echo "wait_for_node: ${remaining} calling '${method}' $i $@"
 
-    while (( SECONDS <= 5 )) && [[ -n "${failed}" ]]; do
-        local check="${NODES[@]}"
+    while (( SECONDS <= timeout )) && [[ -n "${failed}" ]]; do
+        local check="${nodes[@]}"
         failed=
 
         for node in ${check[@]}; do
diff --git a/test/default b/test/default
--- a/test/default
+++ b/test/default
@@ -1,44 +1,42 @@
 #!/bin/bash
 
 source "`dirname ${BASH_SOURCE[0]}`/../scripts/include/call"
+source "`dirname ${BASH_SOURCE[0]}`/../scripts/include/test"
 
 set -e
 
 # Check if we have the right init.
 
-clean_all() {
-    echo "clean all"
-
-    #"${SCRIPT_DIR}/test-delete-all" &> /dev/null; sleep 1
-    "${SCRIPT_DIR}/test-delete-all"; sleep 1
-    "${SCRIPT_DIR}/stop-rtorrent"; sleep 1
-
-    "${SCRIPT_DIR}/config-clear"
-}
-
-start_nodes() {
-    echo "starting clients"
-    "${SCRIPT_DIR}/start-rtorrent"
-
-    echo "waiting for clients"
-    wait_for_nodes "is-client-active"
-}
-
-create_torrents() {
-    "${SCRIPT_DIR}/test-create-all"
-
-    local torrent=
-
-    for torrent in test_h4 test_h6 test_u4 test_u6; do
-        wait_for_nodes is-loaded ${torrent}
-        echo "${torrent}: loaded"
-    done
-}
-
 echo "starting 'default'"
 
 clean_all
+
+# TODO: Set up correct network settings.
+
 start_nodes
 create_torrents
+verify_seeds
 
-echo "done"
+FAILED=0
+
+# TODO: Replace with check to see if we have in-progess.
+sleep 20
+
+set +e
+
+# TODO: Add new test that verifies downloading on machines with both
+# ipv4 and ipv6. Need to add another machine.
+
+verify_completed node2 test_h4 "verifying it works with http4 tracker over ipv4"
+verify_completed node2 test_u4 "verifying it works with udp4 tracker over ipv4"
+verify_completed node3 test_h6 "verifying it works with http6 tracker over ipv6"
+verify_completed node3 test_u6 "verifying it works with udp6 tracker over ipv6"
+
+verify_incompleted node2 test_h6 "verifying it does not work with http6 tracker over ipv4"
+verify_incompleted node2 test_u6 "verifying it does not work with udp6 tracker over ipv4"
+verify_incompleted node3 test_h4 "verifying it does not work with http4 tracker over ipv6"
+verify_incompleted node3 test_u4 "verifying it does not work with udp4 tracker over ipv6"
+
+echo "done: ${FAILED}"
+
+exit ${FAILED}
