Fixed interface 2 use in torrents.

diff --git a/scripts/include/call b/scripts/include/call
--- a/scripts/include/call
+++ b/scripts/include/call
@@ -116,3 +116,14 @@ wait_for_nodes() {
 
     return 0
 }
+
+create_torrent() {
+    echo "creating torrent: $1"
+
+    ${SCRIPT_DIR}/new-torrent "$1" &> /dev/null
+
+    if [ $? -ne 0 ]; then
+        echo "failed to create torrent"
+        exit 1
+    fi
+}
