More stuff.

diff --git a/scripts/include/test b/scripts/include/test
--- a/scripts/include/test
+++ b/scripts/include/test
@@ -1,30 +1,18 @@
 #!/bin/bash
 
-clean_all() {
-    echo "clean all"
-
-    "${SCRIPT_DIR}/test-delete-all"
-    WAIT_TIMEOUT=20 wait_for_nodes is-empty
-
-    "${SCRIPT_DIR}/stop-rtorrent"; sleep 1
-    "${SCRIPT_DIR}/config-clear"
-}
-
-setup_default() {
-    "${SCRIPT_DIR}/build-tracker"
-
-    ${SCRIPT_DIR}/ip-up-4 "node1 node2"
-    ${SCRIPT_DIR}/ip-up-6 "node3"
-    ${SCRIPT_DIR}/ip-down-4 "node3"
-    ${SCRIPT_DIR}/ip-down-6 "node1 node2"
-}
+FAILED=0
 
 start_nodes() {
     echo "starting clients"
     "${SCRIPT_DIR}/start-rtorrent"
 
     echo "waiting for clients"
-    wait_for_nodes "is-client-active"
+
+    if [ -n "${ACTIVE_NODES}" ]; then
+        WAIT_NODES="${ACTIVE_NODES}" wait_for_nodes "is-client-active"
+    else
+        wait_for_nodes "is-client-active"
+    fi
 }
 
 create_torrents() {
@@ -34,7 +22,7 @@ create_torrents() {
 
     # TODO: Use variable.
     for torrent in test_h4 test_h6 test_u4 test_u6; do
-        wait_for_nodes is-loaded ${torrent}
+        WAIT_NODES="${ACTIVE_NODES}" wait_for_nodes is-loaded ${torrent}
         echo "${torrent}: loaded"
     done
 }
@@ -85,4 +73,54 @@ verify_incompleted() {
     fi
 
     return 0
+}
+
+clean_all() {
+    set -e
+
+    echo "clean all"
+
+    "${SCRIPT_DIR}/test-delete-all"
+    WAIT_TIMEOUT=20 wait_for_nodes is-empty
+
+    "${SCRIPT_DIR}/stop-rtorrent"; sleep 1
+    "${SCRIPT_DIR}/config-clear"
+}
+
+setup_default() {
+    "${SCRIPT_DIR}/build-tracker"
+
+    ${SCRIPT_DIR}/ip-up-4 "node1 node2"
+    ${SCRIPT_DIR}/ip-up-6 "node3"
+    ${SCRIPT_DIR}/ip-down-4 "node3"
+    ${SCRIPT_DIR}/ip-down-6 "node1 node2"
+}
+
+setup() {
+    local config=${1:?Missing config setup.}
+
+    echo "setting up config '${config}'"
+
+    case ${config} in
+        "default")
+            setup_default &> /dev/null
+    esac
+
+    start_nodes
+    create_torrents
+    verify_seeds
+
+    # TODO: Replace with check to see if we have in-progess.
+    sleep 20
+    set +e
+}
+
+exit_test() {
+    if [[ ${FAILED} -eq 0 ]]; then
+        echo "done: success"
+    else
+        echo "done: failed:${FAILED}"
+    fi
+
+    exit ${FAILED}
 }
