Add testing scripts.

diff --git a/scripts/test-create-all b/scripts/test-create-all
--- a/scripts/test-create-all
+++ b/scripts/test-create-all
@@ -2,7 +2,18 @@
 
 source `dirname ${BASH_SOURCE[0]}`/include/call
 
-USE_HTTP_TRACKER=yes USE_UDP_TRACKER=no USE_IPV4=yes USE_IPV6=no ${SCRIPT_DIR}/new-torrent test_h4
-USE_HTTP_TRACKER=yes USE_UDP_TRACKER=no USE_IPV4=no USE_IPV6=yes ${SCRIPT_DIR}/new-torrent test_h6
-USE_HTTP_TRACKER=no USE_UDP_TRACKER=yes USE_IPV4=yes USE_IPV6=no ${SCRIPT_DIR}/new-torrent test_u4
-USE_HTTP_TRACKER=no USE_UDP_TRACKER=yes USE_IPV4=no USE_IPV6=yes ${SCRIPT_DIR}/new-torrent test_u6
+create_torrent() {
+    echo "creating torrent: $1"
+
+    ${SCRIPT_DIR}/new-torrent "$1" &> /dev/null
+
+    if [ $? -ne 0 ]; then
+        echo "failed to create torrent"
+        exit 1
+    fi
+}
+
+USE_HTTP_TRACKER=yes USE_UDP_TRACKER=no USE_IPV4=yes USE_IPV6=no create_torrent test_h4
+USE_HTTP_TRACKER=yes USE_UDP_TRACKER=no USE_IPV4=no USE_IPV6=yes create_torrent test_h6
+USE_HTTP_TRACKER=no USE_UDP_TRACKER=yes USE_IPV4=yes USE_IPV6=no create_torrent test_u4
+USE_HTTP_TRACKER=no USE_UDP_TRACKER=yes USE_IPV4=no USE_IPV6=yes create_torrent test_u6
